package com.demo.med.common


const val LOGGEDIN = "LOGGEDIN"
const val USERNAME = "USERNAME"
const val HEALTH = "HEALTH"
const val PRESCRIPTION_LOADED = "PRESCRIPTION_LOADED"
const val MEDICAL_DETAIL = "MEDICAL_DETAIL"
const val DETAIL_SCREEN = "DETAIL_SCREEN"
const val HOME_SCREEN = "HOME_SCREEN"